requirejs.config(
    {
        baseUrl: window.baseURL+"/js/", 
        paths:{
            jquery:["https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min","lib/jquery-1.11.3.min"],
            googleInfobox:"lib/infobox",
            googleMapsLoader:"lib/google-maps-loader",
            slick:"lib/slick.min",
            fancybox:"lib/jquery.fancybox.pack","fancybox-thumbs":"lib/jquery.fancybox-thumbs","fancybox-media":"lib/jquery.fancybox-media",
            select2:"lib/select2.min",
            tooltipster:"lib/jquery.tooltipster.min",
            simpleSlider:"lib/simple-slider.min",
            moment:"lib/moment.min",
            pikaday:"lib/pikaday.min",
            parsley:"lib/parsley.min",
            accounting:"lib/accounting.min",
            i18n_es:"lib/es"
        }, 
        shim:{jquery:{
            exports:"jQuery"
        },
        slick:{
            deps:["jquery"]
        },
        pikaday:{
            deps:["moment"]
        },
        fancybox:{
            deps:["jquery"],
            exports:"Fancybox"
        },
        "fancybox-thumbs":{
            deps:["fancybox"]
        },
        "fancybox-media":{
            deps:["fancybox"]
        },
        select2:{
            deps:["jquery"],
            exports:"Select2"
        },
        i18n_es:{
            deps:["jquery","select2"]
        },
        simpleSlider:{
            deps:["jquery"],
            exports:"SimpleSlider"
        },
        tooltipster:{
            deps:["jquery"],
            exports:"Tooltipster"}
        },
        waitSeconds:60
    }
);